<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'BoilerAppLogger\Doctrine\DBAL\Types\LogRequestMethodEnumType' => __DIR__ . '/src/Logger/Doctrine/DBAL/Types/LogRequestMethodEnum.php',
    'BoilerAppLogger\Entity\LogEntity'                             => __DIR__ . '/src/Logger/Entity/LogEntity.php',
    'BoilerAppLogger\Factory\LoggerServiceFactory'                 => __DIR__ . '/src/Logger/Factory/LoggerServiceFactory.php',
    'BoilerAppLogger\Logger\AbstractLogger'                        => __DIR__ . '/src/Logger/Logger/AbstractLogger.php',
    'BoilerAppLogger\Service\Adapter\DbLogAdapter'                 => __DIR__ . '/src/Logger/Logger/Adapter/DbLoggerAdapter.php',
    'BoilerAppLogger\Logger\Adapter\DoctrineLoggerAdapter'         => __DIR__ . '/src/Logger/Logger/Adapter/DoctrineLoggerAdapter.php',
    'BoilerAppLogger\Service\Adapter\LogAdapterInterface'          => __DIR__ . '/src/Logger/Logger/Adapter/LogAdapterInterface.php',
    'BoilerAppLogger\Logger\Adapter\LoggerAdapterInterface'        => __DIR__ . '/src/Logger/Logger/Adapter/LoggerAdapterInterface.php',
    'BoilerAppLogger\Logger\LoggerInterface'                       => __DIR__ . '/src/Logger/Logger/LoggerInterface.php',
    'BoilerAppLogger\Logger\LoggerTrait'                           => __DIR__ . '/src/Logger/Logger/LoggerTrait.php',
    'BoilerAppLogger\Logger\MvcLogger'                             => __DIR__ . '/src/Logger/Logger/MvcLogger.php',
    'BoilerAppLogger\LoggerService'                                => __DIR__ . '/src/Logger/LoggerService.php',
    'BoilerAppLogger\LoggerServiceConfiguration'                   => __DIR__ . '/src/Logger/LoggerServiceConfiguration.php',
    'BoilerAppLog\Repository\LogRepository'                        => __DIR__ . '/src/Logger/Repository/LogRepository.php',
);
